import sharp from "sharp";
import { mkdir, writeFile } from "node:fs/promises";
await mkdir("public/assets", { recursive: true });
const egg = `<svg xmlns="http://www.w3.org/2000/svg" width="768" height="768" viewBox="0 0 768 768"><defs>
<radialGradient id="shell" cx="32%" cy="28%" r="80%"><stop stop-color="#fff7f1"/><stop offset=".27" stop-color="#e4d6f4"/><stop offset=".65" stop-color="#bca2d7"/><stop offset="1" stop-color="#6f598c"/></radialGradient>
<linearGradient id="gold" x2="1" y2="1"><stop stop-color="#fff5d5"/><stop offset=".45" stop-color="#dfc398"/><stop offset="1" stop-color="#987c69"/></linearGradient>
<radialGradient id="spot"><stop stop-color="#fff" stop-opacity=".8"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>
<filter id="blur"><feGaussianBlur stdDeviation="8"/></filter><clipPath id="clip"><path d="M384 107C311 107 213 253 206 395C198 535 277 607 384 607S570 535 562 395C555 253 457 107 384 107Z"/></clipPath></defs>
<path d="M384 107C311 107 213 253 206 395C198 535 277 607 384 607S570 535 562 395C555 253 457 107 384 107Z" fill="url(#shell)" stroke="#ebd8f5" stroke-width="3"/>
<g clip-path="url(#clip)"><path d="M247 504Q385 587 540 480" fill="none" stroke="#6c5289" stroke-width="16" opacity=".15"/><path d="M223 422Q380 496 562 418M238 313Q380 379 546 316" fill="none" stroke="url(#gold)" stroke-width="3" opacity=".75"/>
<path d="M293 175Q245 325 278 521M475 175Q519 327 487 521" fill="none" stroke="#fff6ea" stroke-width="1.5" opacity=".4"/>
<ellipse cx="301" cy="244" rx="44" ry="96" transform="rotate(24 301 244)" fill="url(#spot)"/><ellipse cx="419" cy="559" rx="117" ry="25" fill="#8f76b7" opacity=".25"/>
<g fill="#fff5e2" opacity=".7"><circle cx="309" cy="219" r="3"/><circle cx="438" cy="272" r="3"/><circle cx="297" cy="410" r="2"/><circle cx="487" cy="449" r="2"/><circle cx="440" cy="511" r="3"/><circle cx="260" cy="341" r="2"/><circle cx="383" cy="171" r="2"/></g></g>
<g transform="translate(384 367)"><path d="M0-63L45 0 0 63-45 0Z" fill="#a78cc3" stroke="url(#gold)" stroke-width="4"/><path d="M0-44L28 0 0 44-28 0Z" fill="#e9d2f8"/><path d="M0-36L0 35-23 0Z" fill="#fbefef"/><path d="M0-36L23 0 0 35Z" fill="#c5a6df"/><path d="M0-26L7-7 24 0 7 7 0 26-7 7-24 0-7-7Z" fill="#fff6df"/></g>
<path d="M371 126Q383 117 396 126M220 439Q210 457 224 483M548 439Q558 457 544 483" fill="none" stroke="#f2e2ca" stroke-width="3"/>
</svg>`;
await sharp(Buffer.from(egg)).png().toFile("public/assets/egg.png");
const palettes = {
  moon: ["#dfd6fc", "#9f89c9", "#615276", "#f2dba7", "#a395de"],
  flora: ["#d6eed0", "#83b394", "#426963", "#f4d8ad", "#8fcabb"],
  ember: ["#f8d3b4", "#d58c7c", "#7e4e64", "#ffe8a9", "#ecb795"],
  tide: ["#c9e9ed", "#7aaabc", "#415f80", "#f7dba8", "#98d4d6"],
};
for (const [name, [light, mid, dark, gold, wing]] of Object.entries(palettes)) {
  const creature = `<svg xmlns="http://www.w3.org/2000/svg" width="768" height="768" viewBox="0 0 768 768"><defs>
<radialGradient id="body" cx="35%" cy="25%" r="85%"><stop stop-color="${light}"/><stop offset=".55" stop-color="${mid}"/><stop offset="1" stop-color="${dark}"/></radialGradient>
<radialGradient id="face" cx="35%" cy="25%" r="85%"><stop stop-color="#fff6e9"/><stop offset=".6" stop-color="${light}"/><stop offset="1" stop-color="${mid}"/></radialGradient>
<linearGradient id="horn" x2=".7" y2="1"><stop stop-color="#fff5d5"/><stop offset="1" stop-color="${gold}"/></linearGradient>
<radialGradient id="iris" cx="45%" cy="60%"><stop stop-color="#709f99"/><stop offset=".5" stop-color="#263744"/><stop offset="1" stop-color="#171e30"/></radialGradient>
<filter id="soft"><feGaussianBlur stdDeviation="6"/></filter></defs>
<!-- A bundled illustrated demo creature. Live monsters are generated by Flare. -->
<path d="M480 523C547 531 604 481 587 399C662 438 683 531 618 574C575 604 503 592 471 566Z" fill="url(#body)" stroke="${dark}" stroke-width="3"/>
<path d="M593 405Q645 453 629 498Q602 477 593 405Z" fill="${gold}"/><path d="M613 473Q627 497 620 521M602 523L610 547" fill="none" stroke="${light}" stroke-width="4" opacity=".5"/>
<path d="M313 458C244 374 214 365 133 338C162 386 162 430 169 479Q202 463 222 483Q242 467 260 493L303 525Z" fill="${wing}" stroke="${dark}" stroke-width="3"/>
<path d="M133 338L260 493M180 380L222 483M228 404L303 525" fill="none" stroke="${light}" stroke-width="5" opacity=".6"/>
<path d="M461 444C509 363 548 344 590 333C573 382 590 418 580 455Q551 444 535 468Q513 454 490 493Z" fill="${wing}" stroke="${dark}" stroke-width="3"/>
<path d="M590 333L490 493M555 375L535 468" fill="none" stroke="${light}" stroke-width="4" opacity=".65"/>
<path d="M313 417C276 445 257 506 269 563C278 607 316 640 393 640C457 640 501 612 505 566C513 509 477 447 442 422Z" fill="url(#body)" stroke="${dark}" stroke-width="3"/>
<ellipse cx="380" cy="543" rx="68" ry="76" fill="${light}" opacity=".8"/><path d="M346 489Q380 506 414 486M337 515Q380 533 428 512M337 544Q380 562 428 540M344 574Q380 591 417 567" fill="none" stroke="#fff7e4" stroke-width="3" opacity=".6"/>
<path d="M287 523Q256 576 286 590Q311 594 328 548M463 523Q497 570 473 588Q448 600 432 549" fill="url(#body)" stroke="${dark}" stroke-width="3"/>
<path d="M308 595Q272 618 293 645Q307 659 353 648L365 613M437 596Q478 612 461 639Q446 656 403 647L398 614" fill="url(#face)" stroke="${dark}" stroke-width="3"/>
<path d="M311 629L314 645M329 630L331 647M428 630L428 645M445 624L447 640" stroke="${mid}" stroke-width="3" stroke-linecap="round"/>
<path d="M280 298Q197 249 214 141Q291 157 326 250M441 254Q470 156 548 149Q555 246 484 299" fill="url(#body)" stroke="${dark}" stroke-width="3"/>
<path d="M278 263Q230 224 232 171Q283 191 300 246M467 254Q491 194 527 177Q525 239 483 275" fill="${gold}" opacity=".85"/>
<path d="M296 254C283 220 297 183 322 169L312 133 337 150 354 115 359 171 341 215 347 245M435 240L428 206 436 167 455 142 460 180 490 161 474 198 467 242" fill="url(#horn)" stroke="${dark}" stroke-width="2"/>
<path d="M261 319C265 254 312 227 381 227C454 227 505 260 509 324L529 354 506 359 520 382 490 380C478 424 433 453 379 451C320 449 276 424 263 387L237 389 250 365 227 358Z" fill="url(#face)" stroke="${dark}" stroke-width="3"/>
<path d="M283 323Q319 289 352 320M414 315Q446 289 475 313" fill="none" stroke="${mid}" stroke-width="9" stroke-linecap="round"/>
<ellipse cx="322" cy="349" rx="31" ry="39" fill="url(#iris)" transform="rotate(-8 322 349)"/><ellipse cx="447" cy="343" rx="28" ry="36" fill="url(#iris)" transform="rotate(7 447 343)"/>
<ellipse cx="315" cy="334" rx="11" ry="13" fill="#fff9e9"/><ellipse cx="440" cy="329" rx="10" ry="12" fill="#fff9e9"/><circle cx="332" cy="365" r="5" fill="${gold}"/><circle cx="457" cy="357" r="4" fill="${gold}"/>
<ellipse cx="281" cy="384" rx="20" ry="9" fill="#efa6b4" opacity=".5" filter="url(#soft)"/><ellipse cx="480" cy="376" rx="18" ry="9" fill="#efa6b4" opacity=".4" filter="url(#soft)"/>
<path d="M372 377Q382 369 392 377L382 386Z" fill="${dark}"/><path d="M382 385L381 396M363 395Q381 412 400 393" fill="none" stroke="${dark}" stroke-width="3.5" stroke-linecap="round"/>
<path d="M383 259L389 274 404 280 389 286 383 302 377 286 362 280 377 274Z" fill="${gold}"/><path d="M321 418L329 421M433 416L441 412" stroke="#fff9ed" stroke-width="4" stroke-linecap="round"/>
<g fill="#fff7e9" opacity=".75"><circle cx="299" cy="289" r="3"/><circle cx="462" cy="281" r="3"/><circle cx="295" cy="473" r="3"/><circle cx="471" cy="494" r="2"/><circle cx="292" cy="496" r="2"/></g>
</svg>`;
  await sharp(Buffer.from(creature))
    .png()
    .toFile(`public/assets/companion-${name}.png`);
}
for (const size of [192, 512]) {
  const icon = `<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" rx="100" fill="#242638"/><circle cx="256" cy="256" r="175" fill="none" stroke="#ad96d1" stroke-width="2"/><path d="M256 116C201 116 142 236 142 307a114 114 0 00228 0C370 236 311 116 256 116" fill="#cbb6e7"/><path d="M266 184L206 276h63l-34 83 82-127h-64z" fill="#fff1c9"/></svg>`;
  await sharp(Buffer.from(icon))
    .resize(size)
    .png()
    .toFile(`public/assets/icon-${size}.png`);
}
await writeFile(
  "public/assets/README.txt",
  "Demo art is original procedural vector artwork rasterized to PNG. It is explicitly marked demo in the app. Live generation uses OpenRouter Flare. Regenerate with npm run assets.\n",
);
console.log("Created egg, four demo creatures and PWA icons.");
